since: 2020

menu:
  - name: 归档
    url: /archives/
  - name: 友链
    url: /friends/
  - name: 留言
    url: /messages/
  - name: 关于
    url: /about/

user:
  avatar: avatar.jpg
  name: haizou
  intro: 一介凡人


socialLink:
  - icon: <i class="sea-font">email</i>
    link: mailto:zou.hai@outlook.com
  - icon: <i class="sea-font">github</i>
    link: https://github.com/hai-zou
  - icon: <i class="sea-font">juejin</i>
    link: https://juejin.cn/user/202789929622183
  - icon: <i class="sea-font">rss</i>
    link: https://luckyzh.cn/rss.xml

waline:
  serverURL: https://waline.luckyzh.cn/

algolia:
  appId: "A6S1DCIE2I"
  apiKey: "ddcd005e9001a4d845451373d4460827"
  indexName: "luckyzh"