name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Determine version bump
        id: determine_version
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $LAST_COMMIT_MSG"
          if [[ "$LAST_COMMIT_MSG" =~ ^fix(\([^\)]+\))?: ]]; then
            echo "patch" > bumpfile
            echo "bump=patch" >> $GITHUB_OUTPUT
          elif [[ "$LAST_COMMIT_MSG" =~ ^feat(\([^\)]+\))?: ]]; then
            echo "minor" > bumpfile
            echo "bump=minor" >> $GITHUB_OUTPUT
          elif [[ "$LAST_COMMIT_MSG" =~ ^refactor(\([^\)]+\))?: ]]; then
            echo "major" > bumpfile
            echo "bump=major" >> $GITHUB_OUTPUT
          else
            echo "No version bump needed"
            echo "bump=none" >> $GITHUB_OUTPUT
          fi

      - name: Set Git Config
        if: steps.determine_version.outputs.bump != 'none'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Bump version and create changelog
        if: steps.determine_version.outputs.bump != 'none'
        run: |
          BUMP_TYPE=$(cat bumpfile)
          npm version $BUMP_TYPE -m "chore(release): %s"

      - name: Push changes
        if: steps.determine_version.outputs.bump != 'none'
        run: |
          git push --follow-tags origin main

      - name: Publish to npm
        if: steps.determine_version.outputs.bump != 'none'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
